M48
; DRILL file {KiCad (6.0.9)} date Mon Jun 19 17:18:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-19T17:18:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0670
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1570
%
G90
G05
T1
X5.6437Y-2.5938
X6.0438Y-2.5938
T2
X5.8438Y-2.5938
T0
M30
